/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.geoip.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.rivetlogic.geoip.service.persistence.GeoipBlocksPK;

import java.io.Serializable;

/**
 * The base model interface for the GeoipBlocks service. Represents a row in the &quot;rivetlogic_geoip_GeoipBlocks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.geoip.model.impl.GeoipBlocksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.geoip.model.impl.GeoipBlocksImpl}.
 * </p>
 *
 * @author charles.rodriguez
 * @see GeoipBlocks
 * @see com.rivetlogic.geoip.model.impl.GeoipBlocksImpl
 * @see com.rivetlogic.geoip.model.impl.GeoipBlocksModelImpl
 * @generated
 */
public interface GeoipBlocksModel extends BaseModel<GeoipBlocks> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a geoip blocks model instance should use the {@link GeoipBlocks} interface instead.
	 */

	/**
	 * Returns the primary key of this geoip blocks.
	 *
	 * @return the primary key of this geoip blocks
	 */
	public GeoipBlocksPK getPrimaryKey();

	/**
	 * Sets the primary key of this geoip blocks.
	 *
	 * @param primaryKey the primary key of this geoip blocks
	 */
	public void setPrimaryKey(GeoipBlocksPK primaryKey);

	/**
	 * Returns the geoname ID of this geoip blocks.
	 *
	 * @return the geoname ID of this geoip blocks
	 */
	public long getGeonameId();

	/**
	 * Sets the geoname ID of this geoip blocks.
	 *
	 * @param geonameId the geoname ID of this geoip blocks
	 */
	public void setGeonameId(long geonameId);

	/**
	 * Returns the start ip of this geoip blocks.
	 *
	 * @return the start ip of this geoip blocks
	 */
	public long getStartIp();

	/**
	 * Sets the start ip of this geoip blocks.
	 *
	 * @param startIp the start ip of this geoip blocks
	 */
	public void setStartIp(long startIp);

	/**
	 * Returns the end ip of this geoip blocks.
	 *
	 * @return the end ip of this geoip blocks
	 */
	public long getEndIp();

	/**
	 * Sets the end ip of this geoip blocks.
	 *
	 * @param endIp the end ip of this geoip blocks
	 */
	public void setEndIp(long endIp);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GeoipBlocks geoipBlocks);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GeoipBlocks> toCacheModel();

	@Override
	public GeoipBlocks toEscapedModel();

	@Override
	public GeoipBlocks toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}