/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.geoip.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rivetlogic.geoip.model.GeoipLocations;
import com.rivetlogic.geoip.service.GeoipLocationsLocalServiceUtil;

/**
 * The extended model base implementation for the GeoipLocations service. Represents a row in the &quot;rivetlogic_geoip_GeoipLocations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GeoipLocationsImpl}.
 * </p>
 *
 * @author charles.rodriguez
 * @see GeoipLocationsImpl
 * @see com.rivetlogic.geoip.model.GeoipLocations
 * @generated
 */
public abstract class GeoipLocationsBaseImpl extends GeoipLocationsModelImpl
	implements GeoipLocations {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a geoip locations model instance should use the {@link GeoipLocations} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			GeoipLocationsLocalServiceUtil.addGeoipLocations(this);
		}
		else {
			GeoipLocationsLocalServiceUtil.updateGeoipLocations(this);
		}
	}
}